/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.people.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.training.people.model.Loans;
import com.liferay.training.people.model.LoansModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Loans service. Represents a row in the &quot;People_Loans&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LoansModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoansImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoansImpl
 * @generated
 */
@JSON(strict = true)
public class LoansModelImpl extends BaseModelImpl<Loans> implements LoansModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loans model instance should use the <code>Loans</code> interface instead.
	 */
	public static final String TABLE_NAME = "People_Loans";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"peopleId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"surname", Types.VARCHAR},
		{"birth", Types.TIMESTAMP}, {"total_loan", Types.FLOAT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("peopleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("surname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birth", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("total_loan", Types.FLOAT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table People_Loans (uuid_ VARCHAR(75) null,peopleId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,surname VARCHAR(75) null,birth DATE null,total_loan DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table People_Loans";

	public static final String ORDER_BY_JPQL = " ORDER BY loans.peopleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY People_Loans.peopleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SURNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PEOPLEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LoansModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _peopleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPeopleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _peopleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Loans.class;
	}

	@Override
	public String getModelClassName() {
		return Loans.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Loans, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Loans, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Loans, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Loans)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Loans, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Loans, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Loans)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Loans, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Loans, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Loans>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Loans.class.getClassLoader(), Loans.class, ModelWrapper.class);

		try {
			Constructor<Loans> constructor =
				(Constructor<Loans>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Loans, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Loans, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Loans, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Loans, Object>>();
		Map<String, BiConsumer<Loans, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Loans, ?>>();

		attributeGetterFunctions.put("uuid", Loans::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Loans, String>)Loans::setUuid);
		attributeGetterFunctions.put("peopleId", Loans::getPeopleId);
		attributeSetterBiConsumers.put(
			"peopleId", (BiConsumer<Loans, Long>)Loans::setPeopleId);
		attributeGetterFunctions.put("groupId", Loans::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Loans, Long>)Loans::setGroupId);
		attributeGetterFunctions.put("companyId", Loans::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Loans, Long>)Loans::setCompanyId);
		attributeGetterFunctions.put("userId", Loans::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Loans, Long>)Loans::setUserId);
		attributeGetterFunctions.put("userName", Loans::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Loans, String>)Loans::setUserName);
		attributeGetterFunctions.put("createDate", Loans::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Loans, Date>)Loans::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Loans::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Loans, Date>)Loans::setModifiedDate);
		attributeGetterFunctions.put("name", Loans::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Loans, String>)Loans::setName);
		attributeGetterFunctions.put("surname", Loans::getSurname);
		attributeSetterBiConsumers.put(
			"surname", (BiConsumer<Loans, String>)Loans::setSurname);
		attributeGetterFunctions.put("birth", Loans::getBirth);
		attributeSetterBiConsumers.put(
			"birth", (BiConsumer<Loans, Date>)Loans::setBirth);
		attributeGetterFunctions.put("total_loan", Loans::getTotal_loan);
		attributeSetterBiConsumers.put(
			"total_loan", (BiConsumer<Loans, Float>)Loans::setTotal_loan);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPeopleId() {
		return _peopleId;
	}

	@Override
	public void setPeopleId(long peopleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_peopleId = peopleId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getSurname() {
		if (_surname == null) {
			return "";
		}
		else {
			return _surname;
		}
	}

	@Override
	public void setSurname(String surname) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_surname = surname;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSurname() {
		return getColumnOriginalValue("surname");
	}

	@JSON
	@Override
	public Date getBirth() {
		return _birth;
	}

	@Override
	public void setBirth(Date birth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birth = birth;
	}

	@JSON
	@Override
	public float getTotal_loan() {
		return _total_loan;
	}

	@Override
	public void setTotal_loan(float total_loan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_total_loan = total_loan;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Loans.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Loans.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Loans toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Loans>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoansImpl loansImpl = new LoansImpl();

		loansImpl.setUuid(getUuid());
		loansImpl.setPeopleId(getPeopleId());
		loansImpl.setGroupId(getGroupId());
		loansImpl.setCompanyId(getCompanyId());
		loansImpl.setUserId(getUserId());
		loansImpl.setUserName(getUserName());
		loansImpl.setCreateDate(getCreateDate());
		loansImpl.setModifiedDate(getModifiedDate());
		loansImpl.setName(getName());
		loansImpl.setSurname(getSurname());
		loansImpl.setBirth(getBirth());
		loansImpl.setTotal_loan(getTotal_loan());

		loansImpl.resetOriginalValues();

		return loansImpl;
	}

	@Override
	public Loans cloneWithOriginalValues() {
		LoansImpl loansImpl = new LoansImpl();

		loansImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		loansImpl.setPeopleId(this.<Long>getColumnOriginalValue("peopleId"));
		loansImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		loansImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		loansImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		loansImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		loansImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		loansImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		loansImpl.setName(this.<String>getColumnOriginalValue("name"));
		loansImpl.setSurname(this.<String>getColumnOriginalValue("surname"));
		loansImpl.setBirth(this.<Date>getColumnOriginalValue("birth"));
		loansImpl.setTotal_loan(
			this.<Float>getColumnOriginalValue("total_loan"));

		return loansImpl;
	}

	@Override
	public int compareTo(Loans loans) {
		int value = 0;

		if (getPeopleId() < loans.getPeopleId()) {
			value = -1;
		}
		else if (getPeopleId() > loans.getPeopleId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Loans)) {
			return false;
		}

		Loans loans = (Loans)object;

		long primaryKey = loans.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Loans> toCacheModel() {
		LoansCacheModel loansCacheModel = new LoansCacheModel();

		loansCacheModel.uuid = getUuid();

		String uuid = loansCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			loansCacheModel.uuid = null;
		}

		loansCacheModel.peopleId = getPeopleId();

		loansCacheModel.groupId = getGroupId();

		loansCacheModel.companyId = getCompanyId();

		loansCacheModel.userId = getUserId();

		loansCacheModel.userName = getUserName();

		String userName = loansCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			loansCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			loansCacheModel.createDate = createDate.getTime();
		}
		else {
			loansCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			loansCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			loansCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		loansCacheModel.name = getName();

		String name = loansCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			loansCacheModel.name = null;
		}

		loansCacheModel.surname = getSurname();

		String surname = loansCacheModel.surname;

		if ((surname != null) && (surname.length() == 0)) {
			loansCacheModel.surname = null;
		}

		Date birth = getBirth();

		if (birth != null) {
			loansCacheModel.birth = birth.getTime();
		}
		else {
			loansCacheModel.birth = Long.MIN_VALUE;
		}

		loansCacheModel.total_loan = getTotal_loan();

		return loansCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Loans, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Loans, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Loans, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Loans)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Loans, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Loans, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Loans, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Loans)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Loans>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _peopleId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _surname;
	private Date _birth;
	private float _total_loan;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Loans, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Loans)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("peopleId", _peopleId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("surname", _surname);
		_columnOriginalValues.put("birth", _birth);
		_columnOriginalValues.put("total_loan", _total_loan);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("peopleId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("surname", 512L);

		columnBitmasks.put("birth", 1024L);

		columnBitmasks.put("total_loan", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Loans _escapedModel;

}