version: "3.9"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ${mysql_volume_name}:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  liferay:
    build:
      context: .
      dockerfile: Dockerfile.lfr
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ${deploy_folder_project}:/opt/liferay/deploy
      - ${liferay_volume_name}:/opt/liferay

volumes:
  ${mysql_volume_name}:
  ${liferay_volume_name}: