/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.people.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Loans service. Represents a row in the &quot;People_Loans&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.people.model.impl.LoansModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.people.model.impl.LoansImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Loans
 * @generated
 */
@ProviderType
public interface LoansModel
	extends BaseModel<Loans>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loans model instance should use the {@link Loans} interface instead.
	 */

	/**
	 * Returns the primary key of this loans.
	 *
	 * @return the primary key of this loans
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loans.
	 *
	 * @param primaryKey the primary key of this loans
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this loans.
	 *
	 * @return the uuid of this loans
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this loans.
	 *
	 * @param uuid the uuid of this loans
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the people ID of this loans.
	 *
	 * @return the people ID of this loans
	 */
	public long getPeopleId();

	/**
	 * Sets the people ID of this loans.
	 *
	 * @param peopleId the people ID of this loans
	 */
	public void setPeopleId(long peopleId);

	/**
	 * Returns the group ID of this loans.
	 *
	 * @return the group ID of this loans
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this loans.
	 *
	 * @param groupId the group ID of this loans
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this loans.
	 *
	 * @return the company ID of this loans
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loans.
	 *
	 * @param companyId the company ID of this loans
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this loans.
	 *
	 * @return the user ID of this loans
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loans.
	 *
	 * @param userId the user ID of this loans
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loans.
	 *
	 * @return the user uuid of this loans
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this loans.
	 *
	 * @param userUuid the user uuid of this loans
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loans.
	 *
	 * @return the user name of this loans
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loans.
	 *
	 * @param userName the user name of this loans
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loans.
	 *
	 * @return the create date of this loans
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loans.
	 *
	 * @param createDate the create date of this loans
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loans.
	 *
	 * @return the modified date of this loans
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loans.
	 *
	 * @param modifiedDate the modified date of this loans
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this loans.
	 *
	 * @return the name of this loans
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this loans.
	 *
	 * @param name the name of this loans
	 */
	public void setName(String name);

	/**
	 * Returns the surname of this loans.
	 *
	 * @return the surname of this loans
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this loans.
	 *
	 * @param surname the surname of this loans
	 */
	public void setSurname(String surname);

	/**
	 * Returns the birth of this loans.
	 *
	 * @return the birth of this loans
	 */
	public Date getBirth();

	/**
	 * Sets the birth of this loans.
	 *
	 * @param birth the birth of this loans
	 */
	public void setBirth(Date birth);

	/**
	 * Returns the total_loan of this loans.
	 *
	 * @return the total_loan of this loans
	 */
	public float getTotal_loan();

	/**
	 * Sets the total_loan of this loans.
	 *
	 * @param total_loan the total_loan of this loans
	 */
	public void setTotal_loan(float total_loan);

	@Override
	public Loans cloneWithOriginalValues();

}